connection: &connection
  adapter: postgresql
  encoding: unicode
  host:     localhost
  pool: 5
  username: adrian
  password: adrian

development:
  <<: *connection
  database: slamar_development

test: &test
  <<: *connection
  database: slamar_test
