# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 410f2c42c06091193d14e153d642759be89776228b194dfc8257bf7743a89a15942bc9c817708a2251c8d299b7b8983def8bc47e1340767c299b3278790cc248

test:
  secret_key_base: 6aa906ec7659e68a0281909f676ac6855d9fd83ce9615c12d3889aaa716893c15cb4a76e4cb9c89fec15d4307fdcbf92abba064abb3bd21cb9d2bd8b604ca7f8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
