//= require jquery
//= require jquery_ujs
//= require turbolinks
//= require_tree 
//= require bootstrap-sprockets
//= require moment
//= require bootstrap-datetimepicker
//= require bootstrap
//= require bootstrap3-typeahead.min
